# This workflow will scan JavaScript files for formatting and linting issues. 
# Keeping as a separate workflow to build and test so that we can see any build and test issues if this workflow fails.

name: Lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  javascript:
    uses: lookupdaily/actions/.github/workflows/lint.yml@main
